jobs:

- job: win64
  displayName: 'Windows 2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - task: DownloadSecureFile@1
    name: R2012b-win64.zip
    inputs:
      secureFile: R2012b-win64.zip

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: R2012b-win64.zip
      destinationFolder: ThirdParty/R2012b

  - script: |
      cmake -G "Visual Studio 15 2017 Win64" -B win64 -DMATLAB_DIR=ThirdParty/R2012b .
      cmake --build win64 --config Release
    displayName: Build sfun_fmurun.mexw64

  - task: PublishPipelineArtifact@1
    inputs:
      path: .
      artifact: win64
